go_library(
    name = "config",
    srcs = glob(["*.go"], exclude = ["*_test.go"]),
    package_name = "github.com/siutsin/telegram-jung2-bot/go/internal/config",
    visibility = ["PUBLIC"],
)

go_test(
    name = "config_test",
    srcs = glob(["*.go"]),
    deps = [
        ":config",
        "//go/vendor/github.com/stretchr/testify/assert:assert",
        "//go/vendor/github.com/stretchr/testify/require:require",
    ],
)
