version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  labels:
  - dependency
  ignore:
  - dependency-name: ava
    versions:
    - ">= 3.a, < 4"
  - dependency-name: serverless
    versions:
    - 2.36.0
    - 2.37.0
    - 2.37.1
  - dependency-name: "@babel/runtime"
    versions:
    - 7.12.13
    - 7.12.17
    - 7.13.0
    - 7.13.1
    - 7.13.16
    - 7.13.2
    - 7.13.4
    - 7.13.6
    - 7.13.7
    - 7.13.8
    - 7.13.9
  - dependency-name: "@babel/plugin-transform-runtime"
    versions:
    - 7.12.13
    - 7.12.15
    - 7.13.0
    - 7.13.1
    - 7.13.10
    - 7.13.2
    - 7.13.4
    - 7.13.5
    - 7.13.6
    - 7.13.7
    - 7.13.8
    - 7.13.9
  - dependency-name: aws-sdk
    versions:
    - 2.834.0
    - 2.836.0
    - 2.837.0
    - 2.838.0
    - 2.839.0
    - 2.840.0
    - 2.841.0
    - 2.842.0
    - 2.843.0
    - 2.844.0
    - 2.845.0
    - 2.846.0
    - 2.847.0
    - 2.849.0
    - 2.850.0
    - 2.851.0
    - 2.852.0
    - 2.853.0
    - 2.854.0
    - 2.855.0
    - 2.856.0
    - 2.857.0
    - 2.858.0
    - 2.859.0
  - dependency-name: webpack
    versions:
    - 5.19.0
    - 5.20.0
    - 5.20.1
    - 5.20.2
    - 5.21.0
    - 5.21.1
    - 5.21.2
    - 5.22.0
    - 5.24.0
    - 5.24.1
    - 5.24.2
    - 5.24.3
  - dependency-name: husky
    versions:
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.13.0
    - 7.13.5
    - 7.13.8
    - 7.13.9
  - dependency-name: serverless-dotenv-plugin
    versions:
    - 3.8.0
    - 3.8.1
  - dependency-name: copy-dynamodb-table
    versions:
    - 2.1.0
    - 2.2.0
    - 2.2.1
  - dependency-name: "@babel/cli"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.13.0
  - dependency-name: pino
    versions:
    - 6.11.1
  - dependency-name: "@babel/core"
    versions:
    - 7.12.13
    - 7.12.16
  - dependency-name: pino-pretty
    versions:
    - 4.4.0
