pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author~=^dependabot(-preview)?\[bot\]$
      - author~=^siutsin$
      - status-success=CI
      - status-success=test (12.x)
      - status-success=test (14.x)
      - status-success=test (15.x)
      - status-success=test
    actions:
      merge:
        method: merge
      delete_head_branch: {}
