pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author~=^dependabot(-preview)?\[bot\]$
      - status-success=test (12.x)
      - status-success=test (14.x)
      - status-success=test (15.x)
    actions:
      merge:
        method: squash
      delete_head_branch: {}
