go_library(
    name = "app",
    srcs = glob(["*.go"], exclude = ["*_test.go"]),
    package_name = "github.com/siutsin/telegram-jung2-bot/internal/app",
    visibility = [
        "//cmd:",
        "//internal/...",
    ],
)

go_test(
    name = "app_test",
    srcs = glob(["*.go"]),
    deps = [
        "//vendor/github.com/stretchr/testify/assert:assert",
        "//vendor/github.com/stretchr/testify/require:require",
        ":app",
    ],
)
