go_library(
    name = "telegram",
    srcs = glob(["*.go"], exclude = ["*_test.go"]),
    package_name = "github.com/siutsin/telegram-jung2-bot/go/internal/telegram",
    visibility = ["PUBLIC"],
)

go_test(
    name = "telegram_test",
    srcs = glob(["*.go"]),
    deps = [
        ":telegram",
        "//go/vendor/github.com/stretchr/testify/assert:assert",
        "//go/vendor/github.com/stretchr/testify/require:require",
    ],
)
