// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/siutsin/telegram-jung2-bot/internal/queue (interfaces: batchMessageSender)
//
// Generated by this command:
//
//	mockgen -destination=action_mock_test.go -package=queue -mock_names batchMessageSender=MockBatchMessageSender . batchMessageSender
//

// Package queue is a generated GoMock package.
package queue

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockBatchMessageSender is a mock of batchMessageSender interface.
type MockBatchMessageSender struct {
	ctrl     *gomock.Controller
	recorder *MockBatchMessageSenderMockRecorder
	isgomock struct{}
}

// MockBatchMessageSenderMockRecorder is the mock recorder for MockBatchMessageSender.
type MockBatchMessageSenderMockRecorder struct {
	mock *MockBatchMessageSender
}

// NewMockBatchMessageSender creates a new mock instance.
func NewMockBatchMessageSender(ctrl *gomock.Controller) *MockBatchMessageSender {
	mock := &MockBatchMessageSender{ctrl: ctrl}
	mock.recorder = &MockBatchMessageSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBatchMessageSender) EXPECT() *MockBatchMessageSenderMockRecorder {
	return m.recorder
}

// SendMessageBatch mocks base method.
func (m *MockBatchMessageSender) SendMessageBatch(ctx context.Context, request SendMessageBatchRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessageBatch", ctx, request)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMessageBatch indicates an expected call of SendMessageBatch.
func (mr *MockBatchMessageSenderMockRecorder) SendMessageBatch(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessageBatch", reflect.TypeOf((*MockBatchMessageSender)(nil).SendMessageBatch), ctx, request)
}
