// Code generated by MockGen. DO NOT EDIT.
// Source: action.go
//
// Generated by this command:
//
//	mockgen -source=action.go -destination=action_mock_test.go -package=queue -mock_names batchMessageSender=MockBatchMessageSender
//

// Package queue is a generated GoMock package.
package queue

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockmessageSender is a mock of messageSender interface.
type MockmessageSender struct {
	ctrl     *gomock.Controller
	recorder *MockmessageSenderMockRecorder
	isgomock struct{}
}

// MockmessageSenderMockRecorder is the mock recorder for MockmessageSender.
type MockmessageSenderMockRecorder struct {
	mock *MockmessageSender
}

// NewMockmessageSender creates a new mock instance.
func NewMockmessageSender(ctrl *gomock.Controller) *MockmessageSender {
	mock := &MockmessageSender{ctrl: ctrl}
	mock.recorder = &MockmessageSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockmessageSender) EXPECT() *MockmessageSenderMockRecorder {
	return m.recorder
}

// SendMessage mocks base method.
func (m *MockmessageSender) SendMessage(ctx context.Context, request SendMessageRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessage", ctx, request)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMessage indicates an expected call of SendMessage.
func (mr *MockmessageSenderMockRecorder) SendMessage(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessage", reflect.TypeOf((*MockmessageSender)(nil).SendMessage), ctx, request)
}

// MockBatchMessageSender is a mock of batchMessageSender interface.
type MockBatchMessageSender struct {
	ctrl     *gomock.Controller
	recorder *MockBatchMessageSenderMockRecorder
	isgomock struct{}
}

// MockBatchMessageSenderMockRecorder is the mock recorder for MockBatchMessageSender.
type MockBatchMessageSenderMockRecorder struct {
	mock *MockBatchMessageSender
}

// NewMockBatchMessageSender creates a new mock instance.
func NewMockBatchMessageSender(ctrl *gomock.Controller) *MockBatchMessageSender {
	mock := &MockBatchMessageSender{ctrl: ctrl}
	mock.recorder = &MockBatchMessageSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBatchMessageSender) EXPECT() *MockBatchMessageSenderMockRecorder {
	return m.recorder
}

// SendMessageBatch mocks base method.
func (m *MockBatchMessageSender) SendMessageBatch(ctx context.Context, request SendMessageBatchRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessageBatch", ctx, request)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMessageBatch indicates an expected call of SendMessageBatch.
func (mr *MockBatchMessageSenderMockRecorder) SendMessageBatch(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessageBatch", reflect.TypeOf((*MockBatchMessageSender)(nil).SendMessageBatch), ctx, request)
}

// MockmessageReceiver is a mock of messageReceiver interface.
type MockmessageReceiver struct {
	ctrl     *gomock.Controller
	recorder *MockmessageReceiverMockRecorder
	isgomock struct{}
}

// MockmessageReceiverMockRecorder is the mock recorder for MockmessageReceiver.
type MockmessageReceiverMockRecorder struct {
	mock *MockmessageReceiver
}

// NewMockmessageReceiver creates a new mock instance.
func NewMockmessageReceiver(ctrl *gomock.Controller) *MockmessageReceiver {
	mock := &MockmessageReceiver{ctrl: ctrl}
	mock.recorder = &MockmessageReceiverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockmessageReceiver) EXPECT() *MockmessageReceiverMockRecorder {
	return m.recorder
}

// ReceiveMessage mocks base method.
func (m *MockmessageReceiver) ReceiveMessage(ctx context.Context, request ReceiveMessageRequest) (ReceiveMessageResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReceiveMessage", ctx, request)
	ret0, _ := ret[0].(ReceiveMessageResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReceiveMessage indicates an expected call of ReceiveMessage.
func (mr *MockmessageReceiverMockRecorder) ReceiveMessage(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReceiveMessage", reflect.TypeOf((*MockmessageReceiver)(nil).ReceiveMessage), ctx, request)
}
