go_binary(
    name = "app",
    srcs = ["main.go"],
    deps = [
        "//internal:internal",
        "//internal/dynamodb:dynamodb",
        "//internal/httpserver:httpserver",
        "//internal/queue:queue",
        "//vendor/github.com/aws/aws-sdk-go-v2/aws:aws",
        "//vendor/github.com/aws/aws-sdk-go-v2/config:config",
        "//vendor/github.com/aws/aws-sdk-go-v2/service/dynamodb:dynamodb",
        "//vendor/github.com/aws/aws-sdk-go-v2/service/sqs:sqs",
    ],
    visibility = ["PUBLIC"],
)

go_test(
    name = "app_test",
    srcs = glob(["*.go"]),
    deps = [
        "//internal:internal",
        "//internal/dynamodb:dynamodb",
        "//internal/httpserver:httpserver",
        "//internal/queue:queue",
        "//vendor/github.com/aws/aws-sdk-go-v2/aws:aws",
        "//vendor/github.com/aws/aws-sdk-go-v2/config:config",
        "//vendor/github.com/aws/aws-sdk-go-v2/service/dynamodb:dynamodb",
        "//vendor/github.com/aws/aws-sdk-go-v2/service/sqs:sqs",
        "//vendor/github.com/stretchr/testify/assert:assert",
        "//vendor/github.com/stretchr/testify/require:require",
    ],
)
