go_binary(
    name = "app",
    srcs = ["main.go"],
    deps = [
        "//internal/app:app",
        "//internal/config:config",
        "//internal/runtime:runtime",
    ],
    visibility = ["PUBLIC"],
)
