// Code generated by MockGen. DO NOT EDIT.
// Source: main.go
//
// Generated by this command:
//
//	mockgen -source=main.go -destination=main_mock_test.go -package=main -mock_names messageEnqueuer=MockMessageEnqueuer
//

// Package main is a generated GoMock package.
package main

import (
	context "context"
	reflect "reflect"
	time "time"

	bot "github.com/siutsin/telegram-jung2-bot/internal"
	queue "github.com/siutsin/telegram-jung2-bot/internal/queue"
	gomock "go.uber.org/mock/gomock"
)

// MockqueueOperator is a mock of queueOperator interface.
type MockqueueOperator struct {
	ctrl     *gomock.Controller
	recorder *MockqueueOperatorMockRecorder
	isgomock struct{}
}

// MockqueueOperatorMockRecorder is the mock recorder for MockqueueOperator.
type MockqueueOperatorMockRecorder struct {
	mock *MockqueueOperator
}

// NewMockqueueOperator creates a new mock instance.
func NewMockqueueOperator(ctrl *gomock.Controller) *MockqueueOperator {
	mock := &MockqueueOperator{ctrl: ctrl}
	mock.recorder = &MockqueueOperatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockqueueOperator) EXPECT() *MockqueueOperatorMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockqueueOperator) Delete(ctx context.Context, request queue.DeleteMessageRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, request)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockqueueOperatorMockRecorder) Delete(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockqueueOperator)(nil).Delete), ctx, request)
}

// DeleteBatch mocks base method.
func (m *MockqueueOperator) DeleteBatch(ctx context.Context, request queue.DeleteMessageBatchRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBatch", ctx, request)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBatch indicates an expected call of DeleteBatch.
func (mr *MockqueueOperatorMockRecorder) DeleteBatch(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBatch", reflect.TypeOf((*MockqueueOperator)(nil).DeleteBatch), ctx, request)
}

// ReceiveMessage mocks base method.
func (m *MockqueueOperator) ReceiveMessage(ctx context.Context, request queue.ReceiveMessageRequest) (queue.ReceiveMessageResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReceiveMessage", ctx, request)
	ret0, _ := ret[0].(queue.ReceiveMessageResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReceiveMessage indicates an expected call of ReceiveMessage.
func (mr *MockqueueOperatorMockRecorder) ReceiveMessage(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReceiveMessage", reflect.TypeOf((*MockqueueOperator)(nil).ReceiveMessage), ctx, request)
}

// SendMessage mocks base method.
func (m *MockqueueOperator) SendMessage(ctx context.Context, request queue.SendMessageRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessage", ctx, request)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMessage indicates an expected call of SendMessage.
func (mr *MockqueueOperatorMockRecorder) SendMessage(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessage", reflect.TypeOf((*MockqueueOperator)(nil).SendMessage), ctx, request)
}

// SendMessageBatch mocks base method.
func (m *MockqueueOperator) SendMessageBatch(ctx context.Context, request queue.SendMessageBatchRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessageBatch", ctx, request)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMessageBatch indicates an expected call of SendMessageBatch.
func (mr *MockqueueOperatorMockRecorder) SendMessageBatch(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessageBatch", reflect.TypeOf((*MockqueueOperator)(nil).SendMessageBatch), ctx, request)
}

// MockmessageAccessor is a mock of messageAccessor interface.
type MockmessageAccessor struct {
	ctrl     *gomock.Controller
	recorder *MockmessageAccessorMockRecorder
	isgomock struct{}
}

// MockmessageAccessorMockRecorder is the mock recorder for MockmessageAccessor.
type MockmessageAccessorMockRecorder struct {
	mock *MockmessageAccessor
}

// NewMockmessageAccessor creates a new mock instance.
func NewMockmessageAccessor(ctrl *gomock.Controller) *MockmessageAccessor {
	mock := &MockmessageAccessor{ctrl: ctrl}
	mock.recorder = &MockmessageAccessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockmessageAccessor) EXPECT() *MockmessageAccessorMockRecorder {
	return m.recorder
}

// QueryByChat mocks base method.
func (m *MockmessageAccessor) QueryByChat(ctx context.Context, tableName string, chatID int64, since time.Time) ([]bot.StoredMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryByChat", ctx, tableName, chatID, since)
	ret0, _ := ret[0].([]bot.StoredMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryByChat indicates an expected call of QueryByChat.
func (mr *MockmessageAccessorMockRecorder) QueryByChat(ctx, tableName, chatID, since any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryByChat", reflect.TypeOf((*MockmessageAccessor)(nil).QueryByChat), ctx, tableName, chatID, since)
}

// Save mocks base method.
func (m *MockmessageAccessor) Save(ctx context.Context, tableName string, row bot.StoredMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, tableName, row)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockmessageAccessorMockRecorder) Save(ctx, tableName, row any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockmessageAccessor)(nil).Save), ctx, tableName, row)
}

// MockchatMaintainer is a mock of chatMaintainer interface.
type MockchatMaintainer struct {
	ctrl     *gomock.Controller
	recorder *MockchatMaintainerMockRecorder
	isgomock struct{}
}

// MockchatMaintainerMockRecorder is the mock recorder for MockchatMaintainer.
type MockchatMaintainerMockRecorder struct {
	mock *MockchatMaintainer
}

// NewMockchatMaintainer creates a new mock instance.
func NewMockchatMaintainer(ctrl *gomock.Controller) *MockchatMaintainer {
	mock := &MockchatMaintainer{ctrl: ctrl}
	mock.recorder = &MockchatMaintainerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockchatMaintainer) EXPECT() *MockchatMaintainerMockRecorder {
	return m.recorder
}

// DueChatIDs mocks base method.
func (m *MockchatMaintainer) DueChatIDs(ctx context.Context, tableName string, timestamp time.Time) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DueChatIDs", ctx, tableName, timestamp)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DueChatIDs indicates an expected call of DueChatIDs.
func (mr *MockchatMaintainerMockRecorder) DueChatIDs(ctx, tableName, timestamp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DueChatIDs", reflect.TypeOf((*MockchatMaintainer)(nil).DueChatIDs), ctx, tableName, timestamp)
}

// Get mocks base method.
func (m *MockchatMaintainer) Get(ctx context.Context, tableName string, chatID int64) (bot.ChatSetting, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, tableName, chatID)
	ret0, _ := ret[0].(bot.ChatSetting)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Get indicates an expected call of Get.
func (mr *MockchatMaintainerMockRecorder) Get(ctx, tableName, chatID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockchatMaintainer)(nil).Get), ctx, tableName, chatID)
}

// Save mocks base method.
func (m *MockchatMaintainer) Save(ctx context.Context, tableName string, settings bot.ChatSetting) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, tableName, settings)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockchatMaintainerMockRecorder) Save(ctx, tableName, settings any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockchatMaintainer)(nil).Save), ctx, tableName, settings)
}

// SaveStatistics mocks base method.
func (m *MockchatMaintainer) SaveStatistics(ctx context.Context, tableName string, chatID int64, userCount, messageCount int, now time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveStatistics", ctx, tableName, chatID, userCount, messageCount, now)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveStatistics indicates an expected call of SaveStatistics.
func (mr *MockchatMaintainerMockRecorder) SaveStatistics(ctx, tableName, chatID, userCount, messageCount, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveStatistics", reflect.TypeOf((*MockchatMaintainer)(nil).SaveStatistics), ctx, tableName, chatID, userCount, messageCount, now)
}

// Update mocks base method.
func (m *MockchatMaintainer) Update(ctx context.Context, update bot.UpdateExpression) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, update)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockchatMaintainerMockRecorder) Update(ctx, update any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockchatMaintainer)(nil).Update), ctx, update)
}

// MocktelegramInteractor is a mock of telegramInteractor interface.
type MocktelegramInteractor struct {
	ctrl     *gomock.Controller
	recorder *MocktelegramInteractorMockRecorder
	isgomock struct{}
}

// MocktelegramInteractorMockRecorder is the mock recorder for MocktelegramInteractor.
type MocktelegramInteractorMockRecorder struct {
	mock *MocktelegramInteractor
}

// NewMocktelegramInteractor creates a new mock instance.
func NewMocktelegramInteractor(ctrl *gomock.Controller) *MocktelegramInteractor {
	mock := &MocktelegramInteractor{ctrl: ctrl}
	mock.recorder = &MocktelegramInteractorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktelegramInteractor) EXPECT() *MocktelegramInteractorMockRecorder {
	return m.recorder
}

// IsAdmin mocks base method.
func (m *MocktelegramInteractor) IsAdmin(ctx context.Context, chatID, userID int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAdmin", ctx, chatID, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsAdmin indicates an expected call of IsAdmin.
func (mr *MocktelegramInteractorMockRecorder) IsAdmin(ctx, chatID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAdmin", reflect.TypeOf((*MocktelegramInteractor)(nil).IsAdmin), ctx, chatID, userID)
}

// SendMessage mocks base method.
func (m *MocktelegramInteractor) SendMessage(ctx context.Context, chatID int64, text string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessage", ctx, chatID, text)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMessage indicates an expected call of SendMessage.
func (mr *MocktelegramInteractorMockRecorder) SendMessage(ctx, chatID, text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessage", reflect.TypeOf((*MocktelegramInteractor)(nil).SendMessage), ctx, chatID, text)
}

// SendMessageWithOptions mocks base method.
func (m *MocktelegramInteractor) SendMessageWithOptions(ctx context.Context, chatID int64, text string, options bot.SendMessageOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessageWithOptions", ctx, chatID, text, options)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMessageWithOptions indicates an expected call of SendMessageWithOptions.
func (mr *MocktelegramInteractorMockRecorder) SendMessageWithOptions(ctx, chatID, text, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessageWithOptions", reflect.TypeOf((*MocktelegramInteractor)(nil).SendMessageWithOptions), ctx, chatID, text, options)
}

// MockscaleUpper is a mock of scaleUpper interface.
type MockscaleUpper struct {
	ctrl     *gomock.Controller
	recorder *MockscaleUpperMockRecorder
	isgomock struct{}
}

// MockscaleUpperMockRecorder is the mock recorder for MockscaleUpper.
type MockscaleUpperMockRecorder struct {
	mock *MockscaleUpper
}

// NewMockscaleUpper creates a new mock instance.
func NewMockscaleUpper(ctrl *gomock.Controller) *MockscaleUpper {
	mock := &MockscaleUpper{ctrl: ctrl}
	mock.recorder = &MockscaleUpperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockscaleUpper) EXPECT() *MockscaleUpperMockRecorder {
	return m.recorder
}

// ScaleUp mocks base method.
func (m *MockscaleUpper) ScaleUp(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ScaleUp", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// ScaleUp indicates an expected call of ScaleUp.
func (mr *MockscaleUpperMockRecorder) ScaleUp(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ScaleUp", reflect.TypeOf((*MockscaleUpper)(nil).ScaleUp), ctx)
}

// MockMessageEnqueuer is a mock of messageEnqueuer interface.
type MockMessageEnqueuer struct {
	ctrl     *gomock.Controller
	recorder *MockMessageEnqueuerMockRecorder
	isgomock struct{}
}

// MockMessageEnqueuerMockRecorder is the mock recorder for MockMessageEnqueuer.
type MockMessageEnqueuerMockRecorder struct {
	mock *MockMessageEnqueuer
}

// NewMockMessageEnqueuer creates a new mock instance.
func NewMockMessageEnqueuer(ctrl *gomock.Controller) *MockMessageEnqueuer {
	mock := &MockMessageEnqueuer{ctrl: ctrl}
	mock.recorder = &MockMessageEnqueuerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageEnqueuer) EXPECT() *MockMessageEnqueuerMockRecorder {
	return m.recorder
}

// Enqueue mocks base method.
func (m *MockMessageEnqueuer) Enqueue(ctx context.Context, action queue.Action) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enqueue", ctx, action)
	ret0, _ := ret[0].(error)
	return ret0
}

// Enqueue indicates an expected call of Enqueue.
func (mr *MockMessageEnqueuerMockRecorder) Enqueue(ctx, action any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enqueue", reflect.TypeOf((*MockMessageEnqueuer)(nil).Enqueue), ctx, action)
}

// Run mocks base method.
func (m *MockMessageEnqueuer) Run(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockMessageEnqueuerMockRecorder) Run(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockMessageEnqueuer)(nil).Run), ctx)
}

// MockqueueRunner is a mock of queueRunner interface.
type MockqueueRunner struct {
	ctrl     *gomock.Controller
	recorder *MockqueueRunnerMockRecorder
	isgomock struct{}
}

// MockqueueRunnerMockRecorder is the mock recorder for MockqueueRunner.
type MockqueueRunnerMockRecorder struct {
	mock *MockqueueRunner
}

// NewMockqueueRunner creates a new mock instance.
func NewMockqueueRunner(ctrl *gomock.Controller) *MockqueueRunner {
	mock := &MockqueueRunner{ctrl: ctrl}
	mock.recorder = &MockqueueRunnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockqueueRunner) EXPECT() *MockqueueRunnerMockRecorder {
	return m.recorder
}

// Run mocks base method.
func (m *MockqueueRunner) Run(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockqueueRunnerMockRecorder) Run(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockqueueRunner)(nil).Run), ctx)
}
