// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/siutsin/telegram-jung2-bot/cmd (interfaces: messageEnqueuer)
//
// Generated by this command:
//
//	mockgen -destination=main_mock_test.go -package=main -mock_names messageEnqueuer=MockMessageEnqueuer . messageEnqueuer
//

// Package main is a generated GoMock package.
package main

import (
	context "context"
	reflect "reflect"

	queue "github.com/siutsin/telegram-jung2-bot/internal/queue"
	gomock "go.uber.org/mock/gomock"
)

// MockMessageEnqueuer is a mock of messageEnqueuer interface.
type MockMessageEnqueuer struct {
	ctrl     *gomock.Controller
	recorder *MockMessageEnqueuerMockRecorder
	isgomock struct{}
}

// MockMessageEnqueuerMockRecorder is the mock recorder for MockMessageEnqueuer.
type MockMessageEnqueuerMockRecorder struct {
	mock *MockMessageEnqueuer
}

// NewMockMessageEnqueuer creates a new mock instance.
func NewMockMessageEnqueuer(ctrl *gomock.Controller) *MockMessageEnqueuer {
	mock := &MockMessageEnqueuer{ctrl: ctrl}
	mock.recorder = &MockMessageEnqueuerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageEnqueuer) EXPECT() *MockMessageEnqueuerMockRecorder {
	return m.recorder
}

// Enqueue mocks base method.
func (m *MockMessageEnqueuer) Enqueue(ctx context.Context, action queue.Action) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enqueue", ctx, action)
	ret0, _ := ret[0].(error)
	return ret0
}

// Enqueue indicates an expected call of Enqueue.
func (mr *MockMessageEnqueuerMockRecorder) Enqueue(ctx, action any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enqueue", reflect.TypeOf((*MockMessageEnqueuer)(nil).Enqueue), ctx, action)
}

// Run mocks base method.
func (m *MockMessageEnqueuer) Run(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockMessageEnqueuerMockRecorder) Run(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockMessageEnqueuer)(nil).Run), ctx)
}
