go_library(
    name = "internal",
    srcs = glob(["*.go"], exclude = ["*_test.go"]),
    package_name = "github.com/siutsin/telegram-jung2-bot/internal",
    deps = [
        "//internal/queue:queue",
        "//vendor/github.com/caarlos0/env/v11:v11",
        "//vendor/github.com/prometheus/client_golang/prometheus:prometheus",
        "//vendor/github.com/prometheus/client_golang/prometheus/promauto:promauto",
        "//vendor/github.com/prometheus/client_golang/prometheus/promhttp:promhttp",
        "//vendor/golang.org/x/sync/errgroup:errgroup",
    ],
    visibility = [
        "//cmd:",
        "//internal/...",
    ],
)

go_test(
    name = "internal_test",
    srcs = glob(["*.go"]),
    deps = [
        "//internal/mock:mock",
        "//internal/queue:queue",
        "//vendor/github.com/caarlos0/env/v11:v11",
        "//vendor/github.com/prometheus/client_golang/prometheus:prometheus",
        "//vendor/github.com/prometheus/client_golang/prometheus/promauto:promauto",
        "//vendor/github.com/prometheus/client_golang/prometheus/promhttp:promhttp",
        "//vendor/github.com/stretchr/testify/assert:assert",
        "//vendor/github.com/stretchr/testify/require:require",
        "//vendor/go.uber.org/mock/gomock:gomock",
        "//vendor/golang.org/x/sync/errgroup:errgroup",
        ":internal",
    ],
)
