// Code generated by MockGen. DO NOT EDIT.
// Source: message_save_worker.go
//
// Generated by this command:
//
//	mockgen -source=message_save_worker.go -destination=message_save_worker_mock_test.go -package=bot -mock_names storedMessageSaver=MockStoredMessageSaver,storedChatSaver=MockStoredChatSaver,queueBatchDeleter=MockQueueBatchDeleter
//

// Package bot is a generated GoMock package.
package bot

import (
	context "context"
	reflect "reflect"

	queue "github.com/siutsin/telegram-jung2-bot/internal/queue"
	gomock "go.uber.org/mock/gomock"
)

// MockStoredMessageSaver is a mock of storedMessageSaver interface.
type MockStoredMessageSaver struct {
	ctrl     *gomock.Controller
	recorder *MockStoredMessageSaverMockRecorder
	isgomock struct{}
}

// MockStoredMessageSaverMockRecorder is the mock recorder for MockStoredMessageSaver.
type MockStoredMessageSaverMockRecorder struct {
	mock *MockStoredMessageSaver
}

// NewMockStoredMessageSaver creates a new mock instance.
func NewMockStoredMessageSaver(ctrl *gomock.Controller) *MockStoredMessageSaver {
	mock := &MockStoredMessageSaver{ctrl: ctrl}
	mock.recorder = &MockStoredMessageSaverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStoredMessageSaver) EXPECT() *MockStoredMessageSaverMockRecorder {
	return m.recorder
}

// Save mocks base method.
func (m *MockStoredMessageSaver) Save(ctx context.Context, tableName string, row StoredMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, tableName, row)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockStoredMessageSaverMockRecorder) Save(ctx, tableName, row any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockStoredMessageSaver)(nil).Save), ctx, tableName, row)
}

// MockStoredChatSaver is a mock of storedChatSaver interface.
type MockStoredChatSaver struct {
	ctrl     *gomock.Controller
	recorder *MockStoredChatSaverMockRecorder
	isgomock struct{}
}

// MockStoredChatSaverMockRecorder is the mock recorder for MockStoredChatSaver.
type MockStoredChatSaverMockRecorder struct {
	mock *MockStoredChatSaver
}

// NewMockStoredChatSaver creates a new mock instance.
func NewMockStoredChatSaver(ctrl *gomock.Controller) *MockStoredChatSaver {
	mock := &MockStoredChatSaver{ctrl: ctrl}
	mock.recorder = &MockStoredChatSaverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStoredChatSaver) EXPECT() *MockStoredChatSaverMockRecorder {
	return m.recorder
}

// Save mocks base method.
func (m *MockStoredChatSaver) Save(ctx context.Context, tableName string, settings ChatSetting) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, tableName, settings)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockStoredChatSaverMockRecorder) Save(ctx, tableName, settings any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockStoredChatSaver)(nil).Save), ctx, tableName, settings)
}

// MockQueueBatchDeleter is a mock of queueBatchDeleter interface.
type MockQueueBatchDeleter struct {
	ctrl     *gomock.Controller
	recorder *MockQueueBatchDeleterMockRecorder
	isgomock struct{}
}

// MockQueueBatchDeleterMockRecorder is the mock recorder for MockQueueBatchDeleter.
type MockQueueBatchDeleterMockRecorder struct {
	mock *MockQueueBatchDeleter
}

// NewMockQueueBatchDeleter creates a new mock instance.
func NewMockQueueBatchDeleter(ctrl *gomock.Controller) *MockQueueBatchDeleter {
	mock := &MockQueueBatchDeleter{ctrl: ctrl}
	mock.recorder = &MockQueueBatchDeleterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueueBatchDeleter) EXPECT() *MockQueueBatchDeleterMockRecorder {
	return m.recorder
}

// DeleteBatch mocks base method.
func (m *MockQueueBatchDeleter) DeleteBatch(ctx context.Context, request queue.DeleteMessageBatchRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBatch", ctx, request)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBatch indicates an expected call of DeleteBatch.
func (mr *MockQueueBatchDeleterMockRecorder) DeleteBatch(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBatch", reflect.TypeOf((*MockQueueBatchDeleter)(nil).DeleteBatch), ctx, request)
}
