// Code generated by MockGen. DO NOT EDIT.
// Source: worker.go
//
// Generated by this command:
//
//	mockgen -source=worker.go -destination=worker_mock_test.go -package=bot -mock_names queueDeleter=MockQueueDeleter,queueReceiver=MockQueueReceiver
//

// Package bot is a generated GoMock package.
package bot

import (
	context "context"
	reflect "reflect"

	queue "github.com/siutsin/telegram-jung2-bot/internal/queue"
	gomock "go.uber.org/mock/gomock"
)

// MockQueueDeleter is a mock of queueDeleter interface.
type MockQueueDeleter struct {
	ctrl     *gomock.Controller
	recorder *MockQueueDeleterMockRecorder
	isgomock struct{}
}

// MockQueueDeleterMockRecorder is the mock recorder for MockQueueDeleter.
type MockQueueDeleterMockRecorder struct {
	mock *MockQueueDeleter
}

// NewMockQueueDeleter creates a new mock instance.
func NewMockQueueDeleter(ctrl *gomock.Controller) *MockQueueDeleter {
	mock := &MockQueueDeleter{ctrl: ctrl}
	mock.recorder = &MockQueueDeleterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueueDeleter) EXPECT() *MockQueueDeleterMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockQueueDeleter) Delete(ctx context.Context, request queue.DeleteMessageRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, request)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockQueueDeleterMockRecorder) Delete(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockQueueDeleter)(nil).Delete), ctx, request)
}

// MockQueueReceiver is a mock of queueReceiver interface.
type MockQueueReceiver struct {
	ctrl     *gomock.Controller
	recorder *MockQueueReceiverMockRecorder
	isgomock struct{}
}

// MockQueueReceiverMockRecorder is the mock recorder for MockQueueReceiver.
type MockQueueReceiverMockRecorder struct {
	mock *MockQueueReceiver
}

// NewMockQueueReceiver creates a new mock instance.
func NewMockQueueReceiver(ctrl *gomock.Controller) *MockQueueReceiver {
	mock := &MockQueueReceiver{ctrl: ctrl}
	mock.recorder = &MockQueueReceiverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueueReceiver) EXPECT() *MockQueueReceiverMockRecorder {
	return m.recorder
}

// ReceiveMessage mocks base method.
func (m *MockQueueReceiver) ReceiveMessage(ctx context.Context, request queue.ReceiveMessageRequest) (queue.ReceiveMessageResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReceiveMessage", ctx, request)
	ret0, _ := ret[0].(queue.ReceiveMessageResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReceiveMessage indicates an expected call of ReceiveMessage.
func (mr *MockQueueReceiverMockRecorder) ReceiveMessage(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReceiveMessage", reflect.TypeOf((*MockQueueReceiver)(nil).ReceiveMessage), ctx, request)
}

// MockqueueConsumer is a mock of queueConsumer interface.
type MockqueueConsumer struct {
	ctrl     *gomock.Controller
	recorder *MockqueueConsumerMockRecorder
	isgomock struct{}
}

// MockqueueConsumerMockRecorder is the mock recorder for MockqueueConsumer.
type MockqueueConsumerMockRecorder struct {
	mock *MockqueueConsumer
}

// NewMockqueueConsumer creates a new mock instance.
func NewMockqueueConsumer(ctrl *gomock.Controller) *MockqueueConsumer {
	mock := &MockqueueConsumer{ctrl: ctrl}
	mock.recorder = &MockqueueConsumerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockqueueConsumer) EXPECT() *MockqueueConsumerMockRecorder {
	return m.recorder
}

// Poll mocks base method.
func (m *MockqueueConsumer) Poll(ctx context.Context, handler func(context.Context, queue.RawMessage) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Poll", ctx, handler)
	ret0, _ := ret[0].(error)
	return ret0
}

// Poll indicates an expected call of Poll.
func (mr *MockqueueConsumerMockRecorder) Poll(ctx, handler any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Poll", reflect.TypeOf((*MockqueueConsumer)(nil).Poll), ctx, handler)
}
