// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/siutsin/telegram-jung2-bot/internal (interfaces: queueReceiver)
//
// Generated by this command:
//
//	mockgen -destination=worker_mock_test.go -package=bot -mock_names queueReceiver=MockQueueReceiver . queueReceiver
//

// Package bot is a generated GoMock package.
package bot

import (
	context "context"
	reflect "reflect"

	queue "github.com/siutsin/telegram-jung2-bot/internal/queue"
	gomock "go.uber.org/mock/gomock"
)

// MockQueueReceiver is a mock of queueReceiver interface.
type MockQueueReceiver struct {
	ctrl     *gomock.Controller
	recorder *MockQueueReceiverMockRecorder
	isgomock struct{}
}

// MockQueueReceiverMockRecorder is the mock recorder for MockQueueReceiver.
type MockQueueReceiverMockRecorder struct {
	mock *MockQueueReceiver
}

// NewMockQueueReceiver creates a new mock instance.
func NewMockQueueReceiver(ctrl *gomock.Controller) *MockQueueReceiver {
	mock := &MockQueueReceiver{ctrl: ctrl}
	mock.recorder = &MockQueueReceiverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueueReceiver) EXPECT() *MockQueueReceiverMockRecorder {
	return m.recorder
}

// ReceiveMessage mocks base method.
func (m *MockQueueReceiver) ReceiveMessage(ctx context.Context, request queue.ReceiveMessageRequest) (queue.ReceiveMessageResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReceiveMessage", ctx, request)
	ret0, _ := ret[0].(queue.ReceiveMessageResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReceiveMessage indicates an expected call of ReceiveMessage.
func (mr *MockQueueReceiverMockRecorder) ReceiveMessage(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReceiveMessage", reflect.TypeOf((*MockQueueReceiver)(nil).ReceiveMessage), ctx, request)
}
