go_library(
    name = "httpserver",
    srcs = glob(["*.go"], exclude = ["*_test.go"]),
    deps = [
        "//internal:internal",
        "//internal/queue:queue",
        "//vendor/go.uber.org/mock/gomock:gomock",
    ],
    package_name = "github.com/siutsin/telegram-jung2-bot/internal/mock/httpserver",
    visibility = [
        "//internal/...",
    ],
)
