// Code generated by MockGen. DO NOT EDIT.
// Source: httpserver.go
//
// Generated by this command:
//
//	mockgen -source=httpserver.go -destination=../mock/httpserver/httpserver_mock.go -package=httpservermock -mock_names messageSaver=MockMessageSaver,chatSaver=MockChatSaver,enqueuer=MockEnqueuer,messenger=MockMessenger,scaleUpper=MockScaleUpper,metricsRecorder=MockMetricsRecorder
//

// Package httpservermock is a generated GoMock package.
package httpservermock

import (
	context "context"
	http "net/http"
	reflect "reflect"

	bot "github.com/siutsin/telegram-jung2-bot/internal"
	queue "github.com/siutsin/telegram-jung2-bot/internal/queue"
	gomock "go.uber.org/mock/gomock"
)

// MockMessageSaver is a mock of messageSaver interface.
type MockMessageSaver struct {
	ctrl     *gomock.Controller
	recorder *MockMessageSaverMockRecorder
	isgomock struct{}
}

// MockMessageSaverMockRecorder is the mock recorder for MockMessageSaver.
type MockMessageSaverMockRecorder struct {
	mock *MockMessageSaver
}

// NewMockMessageSaver creates a new mock instance.
func NewMockMessageSaver(ctrl *gomock.Controller) *MockMessageSaver {
	mock := &MockMessageSaver{ctrl: ctrl}
	mock.recorder = &MockMessageSaverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageSaver) EXPECT() *MockMessageSaverMockRecorder {
	return m.recorder
}

// Save mocks base method.
func (m *MockMessageSaver) Save(ctx context.Context, tableName string, row bot.StoredMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, tableName, row)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockMessageSaverMockRecorder) Save(ctx, tableName, row any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockMessageSaver)(nil).Save), ctx, tableName, row)
}

// MockChatSaver is a mock of chatSaver interface.
type MockChatSaver struct {
	ctrl     *gomock.Controller
	recorder *MockChatSaverMockRecorder
	isgomock struct{}
}

// MockChatSaverMockRecorder is the mock recorder for MockChatSaver.
type MockChatSaverMockRecorder struct {
	mock *MockChatSaver
}

// NewMockChatSaver creates a new mock instance.
func NewMockChatSaver(ctrl *gomock.Controller) *MockChatSaver {
	mock := &MockChatSaver{ctrl: ctrl}
	mock.recorder = &MockChatSaverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChatSaver) EXPECT() *MockChatSaverMockRecorder {
	return m.recorder
}

// Save mocks base method.
func (m *MockChatSaver) Save(ctx context.Context, tableName string, settings bot.ChatSetting) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, tableName, settings)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockChatSaverMockRecorder) Save(ctx, tableName, settings any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockChatSaver)(nil).Save), ctx, tableName, settings)
}

// MockEnqueuer is a mock of enqueuer interface.
type MockEnqueuer struct {
	ctrl     *gomock.Controller
	recorder *MockEnqueuerMockRecorder
	isgomock struct{}
}

// MockEnqueuerMockRecorder is the mock recorder for MockEnqueuer.
type MockEnqueuerMockRecorder struct {
	mock *MockEnqueuer
}

// NewMockEnqueuer creates a new mock instance.
func NewMockEnqueuer(ctrl *gomock.Controller) *MockEnqueuer {
	mock := &MockEnqueuer{ctrl: ctrl}
	mock.recorder = &MockEnqueuerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEnqueuer) EXPECT() *MockEnqueuerMockRecorder {
	return m.recorder
}

// Enqueue mocks base method.
func (m *MockEnqueuer) Enqueue(ctx context.Context, action queue.Action) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enqueue", ctx, action)
	ret0, _ := ret[0].(error)
	return ret0
}

// Enqueue indicates an expected call of Enqueue.
func (mr *MockEnqueuerMockRecorder) Enqueue(ctx, action any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enqueue", reflect.TypeOf((*MockEnqueuer)(nil).Enqueue), ctx, action)
}

// MockMessenger is a mock of messenger interface.
type MockMessenger struct {
	ctrl     *gomock.Controller
	recorder *MockMessengerMockRecorder
	isgomock struct{}
}

// MockMessengerMockRecorder is the mock recorder for MockMessenger.
type MockMessengerMockRecorder struct {
	mock *MockMessenger
}

// NewMockMessenger creates a new mock instance.
func NewMockMessenger(ctrl *gomock.Controller) *MockMessenger {
	mock := &MockMessenger{ctrl: ctrl}
	mock.recorder = &MockMessengerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessenger) EXPECT() *MockMessengerMockRecorder {
	return m.recorder
}

// SendMessage mocks base method.
func (m *MockMessenger) SendMessage(ctx context.Context, chatID int64, text string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessage", ctx, chatID, text)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMessage indicates an expected call of SendMessage.
func (mr *MockMessengerMockRecorder) SendMessage(ctx, chatID, text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessage", reflect.TypeOf((*MockMessenger)(nil).SendMessage), ctx, chatID, text)
}

// MockScaleUpper is a mock of scaleUpper interface.
type MockScaleUpper struct {
	ctrl     *gomock.Controller
	recorder *MockScaleUpperMockRecorder
	isgomock struct{}
}

// MockScaleUpperMockRecorder is the mock recorder for MockScaleUpper.
type MockScaleUpperMockRecorder struct {
	mock *MockScaleUpper
}

// NewMockScaleUpper creates a new mock instance.
func NewMockScaleUpper(ctrl *gomock.Controller) *MockScaleUpper {
	mock := &MockScaleUpper{ctrl: ctrl}
	mock.recorder = &MockScaleUpperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScaleUpper) EXPECT() *MockScaleUpperMockRecorder {
	return m.recorder
}

// ScaleUp mocks base method.
func (m *MockScaleUpper) ScaleUp(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ScaleUp", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// ScaleUp indicates an expected call of ScaleUp.
func (mr *MockScaleUpperMockRecorder) ScaleUp(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ScaleUp", reflect.TypeOf((*MockScaleUpper)(nil).ScaleUp), ctx)
}

// MockMetricsRecorder is a mock of metricsRecorder interface.
type MockMetricsRecorder struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsRecorderMockRecorder
	isgomock struct{}
}

// MockMetricsRecorderMockRecorder is the mock recorder for MockMetricsRecorder.
type MockMetricsRecorderMockRecorder struct {
	mock *MockMetricsRecorder
}

// NewMockMetricsRecorder creates a new mock instance.
func NewMockMetricsRecorder(ctrl *gomock.Controller) *MockMetricsRecorder {
	mock := &MockMetricsRecorder{ctrl: ctrl}
	mock.recorder = &MockMetricsRecorderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricsRecorder) EXPECT() *MockMetricsRecorderMockRecorder {
	return m.recorder
}

// HTTPHandler mocks base method.
func (m *MockMetricsRecorder) HTTPHandler(route string, handler http.Handler) http.Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HTTPHandler", route, handler)
	ret0, _ := ret[0].(http.Handler)
	return ret0
}

// HTTPHandler indicates an expected call of HTTPHandler.
func (mr *MockMetricsRecorderMockRecorder) HTTPHandler(route, handler any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HTTPHandler", reflect.TypeOf((*MockMetricsRecorder)(nil).HTTPHandler), route, handler)
}

// RecordWebhookCommand mocks base method.
func (m *MockMetricsRecorder) RecordWebhookCommand(action string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordWebhookCommand", action)
}

// RecordWebhookCommand indicates an expected call of RecordWebhookCommand.
func (mr *MockMetricsRecorderMockRecorder) RecordWebhookCommand(action any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordWebhookCommand", reflect.TypeOf((*MockMetricsRecorder)(nil).RecordWebhookCommand), action)
}

// RecordWebhookUpdate mocks base method.
func (m *MockMetricsRecorder) RecordWebhookUpdate(outcome string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordWebhookUpdate", outcome)
}

// RecordWebhookUpdate indicates an expected call of RecordWebhookUpdate.
func (mr *MockMetricsRecorderMockRecorder) RecordWebhookUpdate(outcome any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordWebhookUpdate", reflect.TypeOf((*MockMetricsRecorder)(nil).RecordWebhookUpdate), outcome)
}
