// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/siutsin/telegram-jung2-bot/internal/httpserver (interfaces: enqueuer,messenger,scaleUpper)
//
// Generated by this command:
//
//	mockgen -destination=../mock/httpserver/httpserver_mock.go -package=httpservermock -mock_names enqueuer=MockEnqueuer,messenger=MockMessenger,scaleUpper=MockScaleUpper . enqueuer,messenger,scaleUpper
//

// Package httpservermock is a generated GoMock package.
package httpservermock

import (
	context "context"
	reflect "reflect"

	queue "github.com/siutsin/telegram-jung2-bot/internal/queue"
	gomock "go.uber.org/mock/gomock"
)

// MockEnqueuer is a mock of enqueuer interface.
type MockEnqueuer struct {
	ctrl     *gomock.Controller
	recorder *MockEnqueuerMockRecorder
	isgomock struct{}
}

// MockEnqueuerMockRecorder is the mock recorder for MockEnqueuer.
type MockEnqueuerMockRecorder struct {
	mock *MockEnqueuer
}

// NewMockEnqueuer creates a new mock instance.
func NewMockEnqueuer(ctrl *gomock.Controller) *MockEnqueuer {
	mock := &MockEnqueuer{ctrl: ctrl}
	mock.recorder = &MockEnqueuerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEnqueuer) EXPECT() *MockEnqueuerMockRecorder {
	return m.recorder
}

// Enqueue mocks base method.
func (m *MockEnqueuer) Enqueue(ctx context.Context, action queue.Action) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enqueue", ctx, action)
	ret0, _ := ret[0].(error)
	return ret0
}

// Enqueue indicates an expected call of Enqueue.
func (mr *MockEnqueuerMockRecorder) Enqueue(ctx, action any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enqueue", reflect.TypeOf((*MockEnqueuer)(nil).Enqueue), ctx, action)
}

// MockMessenger is a mock of messenger interface.
type MockMessenger struct {
	ctrl     *gomock.Controller
	recorder *MockMessengerMockRecorder
	isgomock struct{}
}

// MockMessengerMockRecorder is the mock recorder for MockMessenger.
type MockMessengerMockRecorder struct {
	mock *MockMessenger
}

// NewMockMessenger creates a new mock instance.
func NewMockMessenger(ctrl *gomock.Controller) *MockMessenger {
	mock := &MockMessenger{ctrl: ctrl}
	mock.recorder = &MockMessengerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessenger) EXPECT() *MockMessengerMockRecorder {
	return m.recorder
}

// SendMessage mocks base method.
func (m *MockMessenger) SendMessage(ctx context.Context, chatID int64, text string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessage", ctx, chatID, text)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMessage indicates an expected call of SendMessage.
func (mr *MockMessengerMockRecorder) SendMessage(ctx, chatID, text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessage", reflect.TypeOf((*MockMessenger)(nil).SendMessage), ctx, chatID, text)
}

// MockScaleUpper is a mock of scaleUpper interface.
type MockScaleUpper struct {
	ctrl     *gomock.Controller
	recorder *MockScaleUpperMockRecorder
	isgomock struct{}
}

// MockScaleUpperMockRecorder is the mock recorder for MockScaleUpper.
type MockScaleUpperMockRecorder struct {
	mock *MockScaleUpper
}

// NewMockScaleUpper creates a new mock instance.
func NewMockScaleUpper(ctrl *gomock.Controller) *MockScaleUpper {
	mock := &MockScaleUpper{ctrl: ctrl}
	mock.recorder = &MockScaleUpperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScaleUpper) EXPECT() *MockScaleUpperMockRecorder {
	return m.recorder
}

// ScaleUp mocks base method.
func (m *MockScaleUpper) ScaleUp(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ScaleUp", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// ScaleUp indicates an expected call of ScaleUp.
func (mr *MockScaleUpperMockRecorder) ScaleUp(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ScaleUp", reflect.TypeOf((*MockScaleUpper)(nil).ScaleUp), ctx)
}
