// Code generated by MockGen. DO NOT EDIT.
// Source: app.go
//
// Generated by this command:
//
//	mockgen -source=app.go -destination=../mock/app_mock.go -package=mock -mock_names httpRunner=MockHTTPRunner,queueRunner=MockQueueWorker
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	net "net"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockHTTPRunner is a mock of httpRunner interface.
type MockHTTPRunner struct {
	ctrl     *gomock.Controller
	recorder *MockHTTPRunnerMockRecorder
	isgomock struct{}
}

// MockHTTPRunnerMockRecorder is the mock recorder for MockHTTPRunner.
type MockHTTPRunnerMockRecorder struct {
	mock *MockHTTPRunner
}

// NewMockHTTPRunner creates a new mock instance.
func NewMockHTTPRunner(ctrl *gomock.Controller) *MockHTTPRunner {
	mock := &MockHTTPRunner{ctrl: ctrl}
	mock.recorder = &MockHTTPRunnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHTTPRunner) EXPECT() *MockHTTPRunnerMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockHTTPRunner) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockHTTPRunnerMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockHTTPRunner)(nil).Close))
}

// Serve mocks base method.
func (m *MockHTTPRunner) Serve(arg0 net.Listener) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Serve", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Serve indicates an expected call of Serve.
func (mr *MockHTTPRunnerMockRecorder) Serve(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Serve", reflect.TypeOf((*MockHTTPRunner)(nil).Serve), arg0)
}

// Shutdown mocks base method.
func (m *MockHTTPRunner) Shutdown(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Shutdown", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Shutdown indicates an expected call of Shutdown.
func (mr *MockHTTPRunnerMockRecorder) Shutdown(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shutdown", reflect.TypeOf((*MockHTTPRunner)(nil).Shutdown), arg0)
}

// MockQueueWorker is a mock of queueRunner interface.
type MockQueueWorker struct {
	ctrl     *gomock.Controller
	recorder *MockQueueWorkerMockRecorder
	isgomock struct{}
}

// MockQueueWorkerMockRecorder is the mock recorder for MockQueueWorker.
type MockQueueWorkerMockRecorder struct {
	mock *MockQueueWorker
}

// NewMockQueueWorker creates a new mock instance.
func NewMockQueueWorker(ctrl *gomock.Controller) *MockQueueWorker {
	mock := &MockQueueWorker{ctrl: ctrl}
	mock.recorder = &MockQueueWorkerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueueWorker) EXPECT() *MockQueueWorkerMockRecorder {
	return m.recorder
}

// Run mocks base method.
func (m *MockQueueWorker) Run(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockQueueWorkerMockRecorder) Run(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockQueueWorker)(nil).Run), arg0)
}
