// Code generated by MockGen. DO NOT EDIT.
// Source: sqs.go
//
// Generated by this command:
//
//	mockgen -source=sqs.go -destination=../mock/queue_mock.go -package=mock -mock_names queueRequester=MockQueueRequester,dependencyObserver=MockQueueDependencyObserver
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	time "time"

	sqs "github.com/aws/aws-sdk-go-v2/service/sqs"
	gomock "go.uber.org/mock/gomock"
)

// MockQueueRequester is a mock of queueRequester interface.
type MockQueueRequester struct {
	ctrl     *gomock.Controller
	recorder *MockQueueRequesterMockRecorder
	isgomock struct{}
}

// MockQueueRequesterMockRecorder is the mock recorder for MockQueueRequester.
type MockQueueRequesterMockRecorder struct {
	mock *MockQueueRequester
}

// NewMockQueueRequester creates a new mock instance.
func NewMockQueueRequester(ctrl *gomock.Controller) *MockQueueRequester {
	mock := &MockQueueRequester{ctrl: ctrl}
	mock.recorder = &MockQueueRequesterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueueRequester) EXPECT() *MockQueueRequesterMockRecorder {
	return m.recorder
}

// DeleteMessage mocks base method.
func (m *MockQueueRequester) DeleteMessage(ctx context.Context, params *sqs.DeleteMessageInput, optFns ...func(*sqs.Options)) (*sqs.DeleteMessageOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteMessage", varargs...)
	ret0, _ := ret[0].(*sqs.DeleteMessageOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteMessage indicates an expected call of DeleteMessage.
func (mr *MockQueueRequesterMockRecorder) DeleteMessage(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMessage", reflect.TypeOf((*MockQueueRequester)(nil).DeleteMessage), varargs...)
}

// ReceiveMessage mocks base method.
func (m *MockQueueRequester) ReceiveMessage(ctx context.Context, params *sqs.ReceiveMessageInput, optFns ...func(*sqs.Options)) (*sqs.ReceiveMessageOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ReceiveMessage", varargs...)
	ret0, _ := ret[0].(*sqs.ReceiveMessageOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReceiveMessage indicates an expected call of ReceiveMessage.
func (mr *MockQueueRequesterMockRecorder) ReceiveMessage(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReceiveMessage", reflect.TypeOf((*MockQueueRequester)(nil).ReceiveMessage), varargs...)
}

// SendMessage mocks base method.
func (m *MockQueueRequester) SendMessage(ctx context.Context, params *sqs.SendMessageInput, optFns ...func(*sqs.Options)) (*sqs.SendMessageOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SendMessage", varargs...)
	ret0, _ := ret[0].(*sqs.SendMessageOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendMessage indicates an expected call of SendMessage.
func (mr *MockQueueRequesterMockRecorder) SendMessage(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessage", reflect.TypeOf((*MockQueueRequester)(nil).SendMessage), varargs...)
}

// MockQueueDependencyObserver is a mock of dependencyObserver interface.
type MockQueueDependencyObserver struct {
	ctrl     *gomock.Controller
	recorder *MockQueueDependencyObserverMockRecorder
	isgomock struct{}
}

// MockQueueDependencyObserverMockRecorder is the mock recorder for MockQueueDependencyObserver.
type MockQueueDependencyObserverMockRecorder struct {
	mock *MockQueueDependencyObserver
}

// NewMockQueueDependencyObserver creates a new mock instance.
func NewMockQueueDependencyObserver(ctrl *gomock.Controller) *MockQueueDependencyObserver {
	mock := &MockQueueDependencyObserver{ctrl: ctrl}
	mock.recorder = &MockQueueDependencyObserverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueueDependencyObserver) EXPECT() *MockQueueDependencyObserverMockRecorder {
	return m.recorder
}

// ObserveDependency mocks base method.
func (m *MockQueueDependencyObserver) ObserveDependency(dependency, operation string, duration time.Duration, err error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ObserveDependency", dependency, operation, duration, err)
}

// ObserveDependency indicates an expected call of ObserveDependency.
func (mr *MockQueueDependencyObserverMockRecorder) ObserveDependency(dependency, operation, duration, err any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ObserveDependency", reflect.TypeOf((*MockQueueDependencyObserver)(nil).ObserveDependency), dependency, operation, duration, err)
}
