// Code generated by MockGen. DO NOT EDIT.
// Source: telegram.go
//
// Generated by this command:
//
//	mockgen -source=telegram.go -destination=mock/telegram_mock.go -package=mock -mock_names dependencyObserver=MockTelegramDependencyObserver
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockTelegramDependencyObserver is a mock of dependencyObserver interface.
type MockTelegramDependencyObserver struct {
	ctrl     *gomock.Controller
	recorder *MockTelegramDependencyObserverMockRecorder
	isgomock struct{}
}

// MockTelegramDependencyObserverMockRecorder is the mock recorder for MockTelegramDependencyObserver.
type MockTelegramDependencyObserverMockRecorder struct {
	mock *MockTelegramDependencyObserver
}

// NewMockTelegramDependencyObserver creates a new mock instance.
func NewMockTelegramDependencyObserver(ctrl *gomock.Controller) *MockTelegramDependencyObserver {
	mock := &MockTelegramDependencyObserver{ctrl: ctrl}
	mock.recorder = &MockTelegramDependencyObserverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTelegramDependencyObserver) EXPECT() *MockTelegramDependencyObserverMockRecorder {
	return m.recorder
}

// ObserveDependency mocks base method.
func (m *MockTelegramDependencyObserver) ObserveDependency(dependency, operation string, duration time.Duration, err error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ObserveDependency", dependency, operation, duration, err)
}

// ObserveDependency indicates an expected call of ObserveDependency.
func (mr *MockTelegramDependencyObserverMockRecorder) ObserveDependency(dependency, operation, duration, err any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ObserveDependency", reflect.TypeOf((*MockTelegramDependencyObserver)(nil).ObserveDependency), dependency, operation, duration, err)
}
