name: govulncheck

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: '22 10 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod

      - name: Scan for reachable vulnerabilities
        uses: geomys/sandboxed-step@7d75eb49d17fdeeb3656b3a57d35932d205bcfb9 # v1.2.1
        with:
          run: |
            GOFLAGS=-mod=mod go run golang.org/x/vuln/cmd/govulncheck@latest ./...
