name: Test Latest Dependencies

on:
  pull_request:
    paths:
      - '.github/workflows/latest-dependencies.yaml'
  schedule:
    - cron: '0 4 * * 0'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod

      - name: Test latest dependencies
        uses: geomys/sandboxed-step@7d75eb49d17fdeeb3656b3a57d35932d205bcfb9 # v1.2.1
        with:
          run: |
            sudo apt-get update -qq
            sudo apt-get install -y -qq clang lld
            ./hack/install-buck2.sh
            export PATH="$HOME/.cargo/bin:$PATH"
            # Keep unreviewed dependency updates out of production to limit supply chain risk.
            # See https://words.filippo.io/dependabot/
            go get -u -t ./...
            make vendor
            make test-only
