name: Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Buck2
        uses: zadlg/buck2-github-composite-action@v3
        with:
          release-tag: latest

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go/go.mod
          cache: true
          cache-dependency-path: go/go.sum

      - name: Run tests
        run: make vendor && make test
